# Configuration for Neovide

# mkdir -p ~/.config/neovide
# ln -s ~/.config/nvim/config.toml ~/.config/neovide/config.toml

frame = "none"

[font]
size = 11
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "JetBrains Mono"
style = "W500"

# fallback font
[[font.normal]]
family = "Vazir Code Hack"
style = "Normal"

[font.features]
"JetBrains Mono" = [ "+calt", "+dlig", "+ss02" ]
