# Configuration for Neovide

# mkdir -p ~/.config/neovide
# ln -s ~/.config/nvim/config.toml ~/.config/neovide/config.toml

frame = "none"

[font]
size = 11
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "Adwaita Mono"

# fallback font
[[font.normal]]
family = "Vazir Code Hack"
style = "Normal"
